In [1]:
import numpy as np
import tensorflow as tf

In [2]:
input_dimension = 10
units = 5
n_inputs_per_node = input_dimension // units

rows = np.arange(input_dimension)
cols = np.arange(units)
cols = np.repeat(cols, n_inputs_per_node)
nonzero_ind = np.column_stack((rows, cols))

In [3]:
rows

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
cols

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4])

In [5]:
nonzero_ind

array([[0, 0],
       [1, 0],
       [2, 1],
       [3, 1],
       [4, 2],
       [5, 2],
       [6, 3],
       [7, 3],
       [8, 4],
       [9, 4]])

In [6]:
kernel = tf.ones((1, input_dimension))

Metal device set to: Apple M1 Pro


2022-05-09 22:09:25.271716: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2022-05-09 22:09:25.271889: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


In [7]:
kernel.shape

TensorShape([1, 10])

In [15]:
x = tf.ones((50, 10))
n_features = x.shape[1]

kernel = tf.reshape(kernel, (1, n_features))
mult = tf.math.multiply(x,kernel)


In [16]:
kernel.shape

TensorShape([1, 10])

In [17]:
mult

<tf.Tensor: shape=(50, 10), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1.,

In [20]:
mult = tf.reshape(mult, (-1, n_inputs_per_node))
mult

<tf.Tensor: shape=(250, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]

In [21]:
mult = tf.math.reduce_sum(mult, axis=1)
mult