In [1]:
from builder_utils import *
from data_reader import load_data
import tensorflow as tf

In [2]:
x, response, samples, cols = load_data('P1000_final_analysis_set_cross_hotspots.csv')

In [3]:
x

AKT1  ANKRD11  ARID1A  ATM  BRAF  CARD11  CDKN1B  CDKN2A  CIC  \
03-082H1_LIVER   0.0      0.0     0.0  0.0   0.0     0.0     0.0     0.0  0.0   
05-116F_LUNG     0.0      0.0     0.0  0.0   0.0     0.0     0.0     0.0  0.0   
05-148E3_LIVER   0.0      0.0     0.0  0.0   0.0     0.0     0.0     0.0  0.0   
05-214BB2_BONE   0.0      0.0     0.0  0.0   0.0     0.0     0.0     0.0  0.0   
07-062F2_LUNG    0.0      0.0     0.0  0.0   0.0     0.0     0.0     0.0  0.0   
...              ...      ...     ...  ...   ...     ...     ...     ...  ...   
TP_2032          0.0      0.0     0.0  0.0   0.0     0.0     0.0     0.0  1.0   
TP_2060          0.0      0.0     0.0  0.0   0.0     0.0     0.0     0.0  0.0   
TP_2064          0.0      0.0     0.0  0.0   0.0     0.0     0.0     0.0  0.0   
TP_2078          0.0      0.0     0.0  0.0   0.0     0.0     0.0     0.0  0.0   
TP_2079          0.0      0.0     0.0  0.0   0.0     0.0     0.0     0.0  0.0   

                CTNNB1  ...  SF3B1  SMAD4  SPOP  STAT3  STK11  TP53  TP63  \
03-082H1_LIVER     0.0  ...    0.0    0.0   0.0    0.0    0.0   1.0   0.0   
05-116F_LUNG       0.0  ...    0.0    0.0   1.0    0.0    0.0   0.0   0.0   
05-148E3_LIVER     1.0  ...    0.0    0.0   0.0    0.0    0.0   0.0   0.0   
05-214BB2_BONE     0.0  ...    0.0    0.0   0.0    0.0    0.0   1.0   0.0   
07-062F2_LUNG      0.0  ...    0.0    0.0   0.0    0.0    0.0   0.0   0.0   
...                ...  ...    ...    ...   ...    ...    ...   ...   ...   
TP_2032            0.0  ...    0.0    0.0   0.0    0.0    0.0   0.0   0.0   
TP_2060            0.0  ...    0.0    0.0   1.0    0.0    0.0   1.0   0.0   
TP_2064            0.0  ...    0.0    0.0   0.0    0.0    0.0   1.0   0.0   
TP_2078            0.0  ...    0.0    0.0   0.0    0.0    0.0   0.0   0.0   
TP_2079            0.0  ...    0.0    0.0   0.0    0.0    0.0   1.0   0.0   

                U2AF1  VHL  XPO1  
03-082H1_LIVER    0.0  0.0   0.0  
05-116F_LUNG      0.0  0.0   0.0  
05-148E3_LIVER    0.0  0.0   0.0  
05-214BB2_BONE    0.0  0.0   0.0  
07-062F2_LUNG     0.0  0.0   0.0  
...               ...  ...   ...  
TP_2032           0.0  0.0   0.0  
TP_2060           0.0  0.0   0.0  
TP_2064           0.0  0.0   0.0  
TP_2078           0.0  0.0   0.0  
TP_2079           0.0  0.0   0.0  

[364 rows x 54 columns]

In [4]:
response.shape

(364,)

In [5]:
x = tf.convert_to_tensor(x)
response = tf.one_hot(tf.convert_to_tensor(response), 2)

Metal device set to: Apple M1 Pro


2022-05-10 00:46:22.058458: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2022-05-10 00:46:22.058729: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


In [6]:
pnet = PNet(cols, cols, 'root_to_leaf', 'tanh', 'sigmoid', 0, True, False, 'lecun_uniform')

layer # 0
pathways 1387
genes 9275
filtered_map (54, 0)
filtered_map (54, 0)
filtered_map (54, 0)
layer # 1
pathways 1066
genes 1399
filtered_map (1387, 0)
filtered_map (1387, 0)
filtered_map (1387, 0)
layer # 2
pathways 447
genes 1068
filtered_map (1066, 0)
filtered_map (1066, 0)
filtered_map (1066, 0)
layer # 3
pathways 147
genes 448
filtered_map (447, 0)
filtered_map (447, 0)
filtered_map (447, 0)
layer # 4
pathways 26
genes 147
filtered_map (147, 0)
filtered_map (147, 0)
filtered_map (147, 0)
layer # 5
pathways 1
genes 26
filtered_map (26, 0)
filtered_map (26, 0)
filtered_map (26, 0)


In [7]:
_, decision_outcome = pnet(tf.convert_to_tensor(x))

input dimension 54 self.units 54
n_inputs_per_node 1


In [8]:
len(decision_outcome)

6

In [12]:
decision_outcome[0]

<tf.Tensor: shape=(364, 2), dtype=float32, numpy=
array([[0.45262784, 0.52023137],
       [0.48788154, 0.49210432],
       [0.49210402, 0.49772564],
       [0.5031663 , 0.5024811 ],
       [0.4865887 , 0.51158106],
       [0.5031663 , 0.5024811 ],
       [0.5031663 , 0.5024811 ],
       [0.5031663 , 0.5024811 ],
       [0.5031663 , 0.5024811 ],
       [0.49526978, 0.5002067 ],
       [0.5031663 , 0.5024811 ],
       [0.500656  , 0.5174521 ],
       [0.5031663 , 0.5024811 ],
       [0.5031663 , 0.5024811 ],
       [0.50892204, 0.53311604],
       [0.5031663 , 0.5024811 ],
       [0.5031663 , 0.5024811 ],
       [0.48603708, 0.48245054],
       [0.5063018 , 0.50493807],
       [0.48788154, 0.49210432],
       [0.4494919 , 0.5177539 ],
       [0.511562  , 0.5014882 ],
       [0.48788154, 0.49210432],
       [0.49789804, 0.5520994 ],
       [0.5031663 , 0.5024811 ],
       [0.5031663 , 0.5024811 ],
       [0.45014125, 0.5351625 ],
       [0.5031663 , 0.5024811 ],
       [0.5031663 , 0.5024

In [10]:
a = pnet.loss(decision_outcome, response)

In [11]:
a

<tf.Tensor: shape=(), dtype=float32, numpy=441.29108>