In [1]:
from builder_utils import *
from data_reader import load_data
import tensorflow as tf

Init Plugin
Init Graph Optimizer
Init Kernel


In [2]:
x, response, samples, cols = load_data('P1000_final_analysis_set_cross_hotspots.csv')

In [3]:
response.shape

(364,)

In [4]:
pnet = PNet(cols, cols, 'root_to_leaf', 'tanh', 'sigmoid', 0, True, False, 'lecun_uniform')

Metal device set to: Apple M1 Pro


2022-05-04 01:46:24.353279: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2022-05-04 01:46:24.353466: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


layer # 0
pathways 1387
genes 9275
filtered_map (54, 0)
filtered_map (54, 0)
filtered_map (54, 0)
layer # 1
pathways 1066
genes 1399
filtered_map (1387, 0)
filtered_map (1387, 0)
filtered_map (1387, 0)
layer # 2
pathways 447
genes 1068
filtered_map (1066, 0)
filtered_map (1066, 0)
filtered_map (1066, 0)
layer # 3
pathways 147
genes 448
filtered_map (447, 0)
filtered_map (447, 0)
filtered_map (447, 0)
layer # 4
pathways 26
genes 147
filtered_map (147, 0)
filtered_map (147, 0)
filtered_map (147, 0)
layer # 5
pathways 1
genes 26
filtered_map (26, 0)
filtered_map (26, 0)
filtered_map (26, 0)


In [5]:
outcome, decision_outcome = pnet(tf.convert_to_tensor(x))

input dimension 54 self.units 54
n_inputs_per_node 1
self.kernel_initializer <tensorflow.python.keras.initializers.initializers_v2.LecunUniform object at 0x29135b7c0>
input dimensions (364, 54)


In [6]:
outcome

<tf.Tensor: shape=(364, 26), dtype=float32, numpy=
array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)>

In [7]:
len(decision_outcome)

6

In [8]:
a = pnet.loss(decision_outcome, response)

100%|████████████████████████████████████████████| 6/6 [00:00<00:00, 146.36it/s]


In [9]:
a

<tf.Tensor: shape=(), dtype=float32, numpy=441.28687>